--- #YAML:1.0
name:                WordNet-SenseRelate-WordToSet
version:             0.03
abstract:            find sense of a target word most related to given set of words
license:             gpl
author:              
    - Ted Pedersen <tpederse at d.umn.edu>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    WordNet::QueryData:            1.37
    WordNet::Similarity:           0.08
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
